name: app_todo_plus
description: Application To-Do & Planning moderne (titre, description, horaires, icône, splash)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  image_picker: ^1.0.7
  emoji_picker_flutter: ^1.6.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  # Décommente si tu as des images/icônes :
  # assets:
  #   - assets/icon.png

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#121212"
  # image: assets/icon.png   # décommente si tu fournis une image
  android: true
  ios: true
